### ISSUE TITLE
Unable to create rent agreement

### ISSUE THREAD

**Issue by eliasmamo** [mfedorov/nebulent-rac-ui#37]
## Here is the sample of the payload i send and the error im receiving. Ive removed all data from customer vehicle and deposit, except for ids. so payload is very small now, but still api replies with 500 error. Let me know if there is something wrong on client side

ID: 64
Address: http://rac.nebulent.com:8080/rac-web/api/v1/rac/orgs/557631da77c8e79044261a00/rentals
Encoding: ISO-8859-1
Http-Method: POST
Content-Type: application/json
Headers: {Accept=[application/json, text/javascript, _/_; q=0.01], accept-encoding=[gzip, deflate], accept-language=[ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4], cache-control=[no-cache], connection=[close], Content-Length=[250], content-type=[application/json], cookie=[sidebar_closed=1; org=%7B%22apikey%22%3A%22haaXK8OeXEZpSshyy61AFfx7K8XuWd8P%22%2C%22id%22%3A%22557631da77c8e79044261a00%22%7D], host=[rac.nebulent.com:8080], origin=[http://localhost:3000], pragma=[no-cache], referer=[http://localhost:3000/?currentMileage=78075&fuelLevel=FULL&daily_rate=50&days=8&type=ACCPAY&discount_rate=&total_discount=], user-agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36], x-requested-with=[XMLHttpRequest]}
## Payload: {"orgId":"557631da77c8e79044261a00","customer":{"contactID":"5576a2130cf208b715c07818"},"vehicle":{"itemID":"1"},"deposit":{"itemID":"5576a2310cf208b715c07819"},"days":2,"subTotal":100,"total":114,"startMileage":78075,"totalTax":14,"discountRate":""}

2015-06-09 04:40:54 ERROR ExceptionMapper:19 - 
java.lang.NullPointerException
    at com.nebulent.rac.rest.services.resources.v1.impl.RacServiceImpl.addRental(RacServiceImpl.java:700)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149)
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:290)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
..........................

**Comment by eliasmamo** [comment]
By trying this and that, figured that its missing location that was not letting agreement to be created. Why location needs to be set explicitly? there is location in vehicle if im not mistaken.. Anyways, this field was not validated before i guess, since previously agreement creation was working. Working now on adding location selection to rent agreement

**Comment by eliasmamo** [comment]
@mfedorov  is it possible to make errors more readable, like there was no clue for me that there is location missing... maybe that would have saved us some time in the future.
